
GENERAL:
    NAME: DEEP_API
    FLASK_ENV: DEVELOPMENT 
    OUTPUT_FOLDER: ./out
    STYLES_FILE: ./support/styles.yaml

ENV_CONFIG:
    COMMON: &common
        DEBUG: True
        DEVELOPMENT: True
    DEVELOPMENT: &development
        <<: *common
    STAGING: &staging
        DEBUG: False
        <<: *common
    PRODUCTION: &production
        <<: *common
        DEBUG: False
        DEVELOPMENT: False

STYLES:
    trippy:
        loi: [inception4a, inception4b]
        epochs: 23
        learning_rate: 0.5
        n_inceptions: 5
        zoom_factor: 0.8
        blend_factor: 0.4
        blur_radius: 60
        size: 256

LOG:
    version: 1
    disable_existing_loggers: True
    formatters:
        standard:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        color_format:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
            (): utils.log_extension.ColoredFormatter
            use_color: true
    handlers:
        console_handler:
            formatter: color_format 
            level: DEBUG
            class: logging.StreamHandler
            stream: ext://sys.stdout
        file_handler:
            formatter: standard
            level: INFO
            class: logging.handlers.RotatingFileHandler
            filename: ./out/deep_api.log

    loggers:
        DEEP_API:
            level: DEBUG
            handlers: [console_handler, file_handler]
        werkzeug:
            level: DEBUG
            handlers: [console_handler, file_handler]
