
GENERAL:
    NAME: DEEP_API
    FLASK_ENV: DEVELOPMENT 
    OUTPUT_FOLDER: ./out

ENV_CONFIG:
    COMMON: &common
        DEBUG: True
        DEVELOPMENT: True
        SECRET_KEY: insecure
    DEVELOPMENT: &development
        <<: *common
    STAGING: &staging
        DEBUG: False
        <<: *common
    PRODUCTION: &production
        <<: *common
        DEBUG: False
        DEVELOPMENT: False
        SECRET_KEY: very_fckn_secure 

MODEL:
    WEIGHTS_PATH: ./model/googlenet_weights.pth
    LOI: [inception5a, inception5b]

LOG:
    version: 1
    disable_existing_loggers: True
    formatters:
        standard:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        color_format:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
            (): utils.log_extension.ColoredFormatter
            use_color: true
    handlers:
        console_handler:
            formatter: color_format 
            level: DEBUG
            class: logging.StreamHandler
            stream: ext://sys.stdout
        file_handler:
            formatter: standard
            level: INFO
            class: logging.handlers.RotatingFileHandler
            filename: ./out/deep_api.log

    loggers:
        DEEP_API:
            level: DEBUG
            handlers: [console_handler, file_handler]
        werkzeug:
            level: DEBUG
            handlers: [console_handler, file_handler]
