
NAME: ITT 
FLASK_ENV: DEBUG
OUTPUT_FOLDER: ./out

SERVER:
    CONFIG:
        COMMON: &common
            DEBUG: True
            DEVELOPMENT: True
            SECRET_KEY: insecure
        DEVELOPMENT: &development
            <<: *common
        STAGING: &staging
            DEBUG: False
            <<: *common
        PRODUCTION: &production
            <<: *common
            DEBUG: False
            DEVELOPMENT: False
            SECRET_KEY: very_fckn_secure 
