# Deep API Lint with PyCodeStyle and Test with UnitTest #

name: Deep Workflow! 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        pip install -r ./support/requirements/dev.txt
    - name: Lint
      run: |
        pycodestyle deep_api
    - name: Test
      run: |
        python test
